version: '3.7'
services:
    {{template_name}}_postgres:
        image: postgres:13.8
        restart: always
        env_file:
          - .env
        ports:
          - '5432:5432'
        volumes:
          - postgres:/var/lib/postgresql/data
          # if want sql to run at startup, can use below
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    {{template_name}}_api:
        build:
          context: .
          target: start_app
        ports:
          - "8080:8080"
        volumes:
        - ./:/usr/src/app
        depends_on:
          - {{template_name}}_postgres
        env_file:
          - .env
volumes:
  postgres:


# docker-compose run web alembic revision --autogenerate -m "First migration"

# docker-compose run web alembic upgrade head